Merge CLI into main
LUMC/SSLP-Analyzer pull request #5
Opened 2023-06-13 13:40 UTC by Timmerman73

2023-06-14 13:50 UTC, Timmerman73 commented
CLI is considered finished and ready for review.

2023-06-15 14:25 UTC, ifokkema requested changes
Some changes are required - please see my comments in the code.
Also, a general comment; the script should always output at least one empty line before it exits; otherwise, the terminal will do something weird.

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/FSHD/FSHD.py
> +    if validate_combinations(args):
The function lets me do:
`python3 FSHD.py -s 1 2 3 4 -p African -A haplotypes.json`
I was looking for the documented method of providing an alternative JSON file, but it was trying to add `haplotypes.json` to itself.
Valid combinations are a nice way to check, but you also need to exclude certain combinations.

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +This Python script allows you to predict genotypes from Short Sequence Length Polymorphisms (SSLPs) values for Facioscapulohumeral muscular dystrophy (FSHD) analysis. It requires a selection of SSLPs
region=population :wink:
I suggest: "(...) the population to which the individual belongs, from where the sample is derived."

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +This analayser can also be used as a standalone pip package. It can be installed by navigating to the FSHD_CLI directory and executing the following command in your enviroment of choice.
You need a spell-checker :wink:

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +The script uses pre-defined haplotypes for prediction. A haplotype is a group of genes within an organism that was inherited together from a single parent. This script uses haplotypes of certain popu
This definition of a haplotype isn't fully correct - please have a look.
Also, the script is actually trying to predict the exact haplotypes present in the patient. Genotypes isn't wrong, but I don't feel the sentence fully explains the script's function.

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +You can also provide an optional input JSON file that contains the haplotypes. If no file is provided, the script uses default haplotypes.
I didn't find this feature; are you sure it's present?

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +Python FSHD.py -s 159 161 163 166 -p European -n 10
This wouldn't run because of the capital P in `Python`.

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +shell
Markup is missing here - this is supposed to be a header, right?

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +Output
Markup is missing here - this is supposed to be a header, right?

2023-06-15 14:25 UTC, ifokkema commented on FSHD_CLI/README.md
> +Note
Markup is missing here - this is supposed to be a header, right?

2023-12-06 16:11 UTC, ifokkema commented on FSHD_CLI/README.md
> +This Python script allows you to predict genotypes from Short Sequence Length Polymorphisms (SSLPs) values for Facioscapulohumeral muscular dystrophy (FSHD) analysis. It requires a selection of SSLPs
Fixed in aaf66dc.

2023-12-06 16:12 UTC, ifokkema commented on FSHD_CLI/README.md
> +This analayser can also be used as a standalone pip package. It can be installed by navigating to the FSHD_CLI directory and executing the following command in your enviroment of choice.
Fixed in aaf66dc.

2023-12-06 16:12 UTC, ifokkema commented on FSHD_CLI/README.md
> +You can also provide an optional input JSON file that contains the haplotypes. If no file is provided, the script uses default haplotypes.
Fixed in aaf66dc.

2023-12-06 16:12 UTC, ifokkema commented on FSHD_CLI/README.md
> +Python FSHD.py -s 159 161 163 166 -p European -n 10
Fixed in aaf66dc.

2023-12-06 16:12 UTC, ifokkema commented on FSHD_CLI/README.md
> +Output
Fixed in aaf66dc.

2023-12-06 16:12 UTC, ifokkema commented on FSHD_CLI/README.md
> +Note
Fixed in aaf66dc.

2023-12-07 10:05 UTC, merged